version: '3.3'

services:

  data_api:
    build: ./data_api/
    image: 127.0.0.1:5000/stack_demo #stackdemo_data_api
    expose:
      - 8801
    env_file:
      - models.env


  nginx:
    build: ./nginx/
    image: 127.0.0.1:5000/stack_demo #stackdemo_nginx
    ports:
      - "80:80"
