version: '3.3'

services:

  data_api:
    #build: ./data_api/
    # image: stackdemo_data_api:1.0
    build: .
    image: 127.0.0.1:5000/docker_swarm_demo/stack_demo/data_api
    expose:
      - 8801
    env_file:
      - models.env


  nginx:
    #build: ./nginx/
    # image: stackdemo_nginx:1.0
    build: .
    image: 127.0.0.1:5000/docker_swarm_demo/stack_demo/nginx
    ports:
      - "80:80"
