version: '3.3'

services:

  db:
    container_name: db
    build: ./DataBase/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: root
      MYSQL_HOST: localhost
      MYSQL_DATABASE: IoT
    ports:
      - "3306:3306"